/*
 * Actions for the Reports (v2)
 */

const actions = {
  SET_FILTER: 'esmiley/reports/SET_FILTER',

  QUERY_DASHBOARD_REGISTRATIONS_REQUEST: 'esmiley/reports/QUERY_DASHBOARD_REGISTRATIONS_REQUEST',
  QUERY_DASHBOARD_REGISTRATIONS_SUCCESS: 'esmiley/reports/QUERY_DASHBOARD_REGISTRATIONS_SUCCESS',
  QUERY_DASHBOARD_REGISTRATIONS_FAILURE: 'esmiley/reports/QUERY_DASHBOARD_REGISTRATIONS_FAILURE',

  QUERY_DASHBOARD_PROJECTS_REQUEST: 'esmiley/reports/QUERY_DASHBOARD_PROJECTS_REQUEST',
  QUERY_DASHBOARD_PROJECTS_SUCCESS: 'esmiley/reports/QUERY_DASHBOARD_PROJECTS_SUCCESS',
  QUERY_DASHBOARD_PROJECTS_FAILURE: 'esmiley/reports/QUERY_DASHBOARD_PROJECTS_FAILURE',

  QUERY_DASHBOARD_SALES_REQUEST: 'esmiley/reports/QUERY_DASHBOARD_SALES_REQUEST',
  QUERY_DASHBOARD_SALES_SUCCESS: 'esmiley/reports/QUERY_DASHBOARD_SALES_SUCCESS',
  QUERY_DASHBOARD_SALES_FAILURE: 'esmiley/reports/QUERY_DASHBOARD_SALES_FAILURE',

  QUERY_REQUEST: 'esmiley/reports/QUERY_REQUEST',
  QUERY_SUCCESS: 'esmiley/reports/QUERY_SUCCESS',
  QUERY_FAILURE: 'esmiley/reports/QUERY_FAILURE',

  QUERY_PROJECTS_REQUEST: 'esmiley/reports/QUERY_PROJECTS_REQUEST',
  QUERY_PROJECTS_SUCCESS: 'esmiley/reports/QUERY_PROJECTS_SUCCESS',
  QUERY_PROJECTS_FAILURE: 'esmiley/reports/QUERY_PROJECTS_FAILURE',

  SET_ACCOUNT_IDS: 'esmiley/reports/SET_ACCOUNT_IDS',
  SET_SELECTED_PROJECT: 'esmiley/reports/SET_SELECTED_PROJECT',

  SET_FILTER_ITEMS: 'esmiley/reports/SET_FILTER_ITEMS',

  MODIFY_FILTER: 'esmiley/reports/MODIFY_FILTER',

  RESET_FILTER: 'esmiley/reports/RESET_FILTER',

  SET_SEARCH_CRITERIA: 'esmiley/reports/SET_SEARCH_CRITERIA',

  QUERY_REPORT_REGISTRATION_POINTS: 'esmiley/reports/QUERY_REPORT_REGISTRATION_POINTS',

  SET_PERIOD: 'esmiley/reports/SET_PERIOD',

  INIT_POINTS: 'esmiley/reports/INIT_POINTS'

};

export default actions;
